import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/header";
import GravityProvider from "@/components/providers/gravity-provider";
import QueryProvider from "@/components/providers/query-provider";

import "./globals.css";

import "@gravity-ui/uikit/styles/fonts.css";
import "@gravity-ui/uikit/styles/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <GravityProvider>
            <Navbar />
            <main className="pt-32 h-full container mx-auto">{children}</main>
          </GravityProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
