import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/header";
import Provider from "@/components/provider";

import "./globals.css";

import "@gravity-ui/uikit/styles/fonts.css";
import "@gravity-ui/uikit/styles/styles.css";
import QueryProvider from "@/components/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Navbar />
          <main className="pt-32 h-full container mx-auto">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
